### PR TITLE
Add --keep-template flag

### PR DESCRIPTION
**Pull request by lwille**
More compatibility with [/andreasjansson/envtpl]() which also supports keeping the template.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
I _think_ the way this works will interfere with the way `--help` is working.

Can we either switch everything to use `flags` or not use `flags` at all? I'd prefer to not bring in flags if we don't need to and it's relatively easy to just check if `--keep-template` is in args, just like I was doing for `--help`.

My reasoning for not wanting to bring in flags is the logic needed here is so trivial, and I'd rather not bloat the binary from another import.

**Comment by lwille** [comment]
Ok this is really straight forward. If you look in the intermediate WIP commit, there's another way of doing this that could be handy (allowing for multiple templates, but also requiring more logic to be implemented). 

Let me know what you think; I think we can go for this very simple solution.

**Comment by lwille** [comment]
Still I must say: I prefer code readability and simplicity (= i.e. using `flags`) over executable size (we're talking a few hundred bytes), and `flags` is a core package.

**Comment by lwille** [comment]
New proposal in new PR #4, I'm rebasing & squashing this branch

**Comment by lwille** [comment]
@mattrobenolt what do you say?

**Comment by lwille** [comment]
closing outdated PR

**Pull request closed without merging**
